name: Check for Changeset Bump File

on:
  pull_request:
    branches:
      - main

jobs:
  check-changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for .changeset/*.md files
        run: |
          count=$(find ./.changeset -type f -name "*.md" | wc -l)
          if [ "$count" -eq "0" ]; then
            echo "❌ No bump file found in .changeset/"
            exit 1
          else
            echo "✅ Found $count bump file(s) in .changeset/"
          fi
